In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('Self Awareness Dataset.csv')

dataset.columns


Index(['Date', 'Number', 'Day', 'Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour', 'End of the day Feeling (0 to 10)',
       'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12'],
      dtype='object')

In [26]:
X.tail()

Sleep Hour  Exercise Hour  Study Hour  StudyDS Hour  Work Hour
60           7              4           3             0          4
61           8              2           2             2          3
62           7              4           4             0          2
63           9              2           0             0          2
64           9              2           0             0          0

In [19]:
X = dataset[['Sleep Hour', 'Exercise Hour', 'Study Hour',
       'StudyDS Hour', 'Work Hour']]
y = dataset[['Number']]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 12, train_size = 48, random_state = 42)

In [21]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [22]:
print('Coefficients', regressor.coef_)
print('Intercept', regressor.intercept_)

Coefficients [[-0.09284167 -0.45818231  0.02842088 -1.05891186 -0.76279477]]
Intercept [7.77565456]


In [23]:
y_pred = regressor.predict(X_test)

In [24]:
y_pred

array([[2.14143387],
       [2.3271172 ],
       [4.59096705],
       [1.8240321 ],
       [1.860032  ],
       [1.76719033],
       [7.0253422 ],
       [1.91687377],
       [6.02371493],
       [7.11818387],
       [1.860032  ],
       [7.0253422 ]])

In [27]:
regressor.predict([[7,4,3,0,4]])

array([[2.3271172]])

In [28]:
regressor.predict([[8,2,2,2,3]])

array([[1.76719033]])

In [29]:
regressor.predict([[7,4,4,0,2]])

array([[3.88112764]])

In [30]:
regressor.predict([[9,2,0,0,2]])

array([[4.49812538]])

In [31]:
regressor.predict([[9,2,0,0,0]])

array([[6.02371493]])

In [32]:
from sklearn.metrics import r2_score
print('r2_score', r2_score(y_test, y_pred))

r2_score 0.8813002229608442
